task_fetch_licitacoes:
  description: >
    Faça uma requisição à API REST e recupere todas as licitações disponíveis no sistema.
  expected_output: >
    Lista de licitações com todos os campos retornados pela API.
  agent: api_agent

task_filtrar_abertas:
  description: >
    A partir da lista de licitações coletadas, filtre somente as que estiverem com status "aberta"
    e extraia os itens solicitados para cada uma delas.
  expected_output: >
    Lista contendo somente licitações abertas com seus respectivos itens.
  agent: filter_agent

task_salvar_json:
  description: >
    Salve a lista de licitações abertas e seus itens no arquivo chamado "licitacoes_abertas.json".
  expected_output: >
    Um arquivo JSON salvo no diretório do projeto com os dados tratados.
  agent: json_agent
